### ISSUE TITLE
Remove Log.class.inc as it doesn't work

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#3833]
## Background

The [Log class](https://github.com/aces/Loris/blob/20.0-release/php/libraries/Log.class.inc) is only used by [survey.php](https://github.com/aces/Loris/blob/20.0-release/htdocs/survey.php).

At this time survey is often configured to write to a file containing a date in its name... however Log only appends to this file and does not create it if it doesn't exist.

Because of these bugs and others we've decided to deprecate the Log class and amend the survey file accordingly. The survey module is being re-written (https://github.com/aces/Loris/pull/3609) so the changes can simply be to remove references to Log. As logging wasn't configured properly in the first place we don't need to worry about losing functionality by not logging survey requests.

As such, this should be a good first issue for someone looking for an entry point to our project. I've outlined the tasks below.

## This improves LORIS by

Getting rid of old cruft!

## TODO

- [ ] Delete the file `php/libraries/Log.class.inc`.

- [ ] Remove the logRequest() function in `survey.php`

- [ ] Verify that Log is not used elsewhere.

**Comment by driusan** [comment]
Fixed by #3999
