### ISSUE TITLE
Rename CenterID of the candidate table to RegistrationCenterID (part 1 of candidate's CenterID refactoring)

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#4057]
This will be part 1 of the future for the `CenterID` field of the candidate table plan (as discussed in September 2018 with @samirdas @driusan and @ridz1208, see [meetings notes](https://docs.google.com/document/d/1N8hTttvWxfmx3iLhURo-XRsXmK4R-0w24RZat98yDls/edit#heading=h.3vek10m5m7pg)).

## TODOs:

Rename the `CenterID` field column of the `candidate` table to `RegistrationCenterID`, which correspond to the `CenterID` at which the candidate was first registered. This should never be changed for a given candidate. 

**The future PR should include:**
- [x] the change of the SQL column name to `RegistrationCenterID`
- [x] the updates to some of the queries in the code to use that new column name 
- [x] the changes of some of the queries to use `s.CenterID` when possible (ensure there is not duplication of the data displayed when doing so and that it does not affect the numbers)

**Extra notes to not forget for this PR:**
- [x] *tools directory:* grep for `c.CenterID` and `CenterID` and check if need to replace it by `s.CenterID` or `c.RegistrationCenterID`
- [x] *Raisinbread dataset:* might need to be fixed for this PR
- [x] *Test suites:* they might most probably break
- [x] *API v0.0.3-dev*
- [x] *API v0.0.2* (only MySQL queries should be fixed according to @driusan)
- [x] Update LORIS-MRI code as well with new field name

**Development notes:**
- [x] DICOM archive is breaking. Bug in the major branch unrelated to the `candidate`'s `CenterID` field renaming (see issue #4067)
- [x] view session of the image browser is breaking. Bug in the major branch unrelated to the `candidate`'s `CenterID` field renaming (see issue #4068)
- [x] need to test the genomic browser
- [x] need to test issue tracker
- [x] need to test media

## Future labels for the PR:

- **SQL**
- **[branch] major**
- **Add to release notes**, **Document at release** and **Notes for existing projects**: the `RegistrationCenterID` should never be changed for a given `candidate`. The `session` table will have the information about the latest `CenterID` the candidate has been seen.
- **Caveat for existing projects**: make sure that `c.CenterID` is replaced by `c.RegistrationCenterID` in your project code queries.

**Comment by cmadjar** [comment]
@driusan @ridz1208 Should I update the queries of API v0.0.2? Updated v0.0.3-dev so far. Waiting for your feedback on this one.

PS: just realized this place is probably better to ask you than Slack so everything is in the issue ;)

**Comment by cmadjar** [comment]
PR was merged. First part of the mission done!
