### ISSUE TITLE
Migrate documentation from GitHub Wiki to version control

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4196]
There has been a plan for some time to version-control our wiki pages to avoid hotfixing but also to keep it synchronized across different releases.

Read The Docs has been proposed as a solution to the problem.

At the end of this process the Wiki should be deprecated. It has already been archived as-is by @ridz1208.

### TODO
- [ ] As a team, review the documentation so that it is up-to-date with an upcoming MAJOR release (e.g. Loris 21)
- [x] Use Read the Docs to create a hosted solution for readable LORIS docs.
    * e.g. http://docs.datalad.org
- [ ] Delete old wiki ONLY when the previous two steps are complete

**Comment by christinerogers** [comment]
Would be good to know... if there isn't already a service that would just collate markdown files from the codebase into perusable pages, i.e. dynamically generating a Read-the-Docs-style site from GitHub.

**Comment by johnsaigle** [comment]
I think that's what Read the Docs does essentially. I'm just not sure on the web-hosting aspects of it. But it does dynamically generate pages from markdown

**Comment by christinerogers** [comment]
Great, I couldn't quite find in their documentation where you could configure the build-refresh (lots of info though about how to import one-time).

**Comment by johnsaigle** [comment]
Pull request #5242 has a proof-of-concept set up for ReadTheDocs. It allows us to import our existing Markdown files into their service so that they render nicely.

**Comment by gdevenyi** [comment]
The wiki is version controlled... https://github.com/aces/Loris.wiki.git

**Comment by johnsaigle** [comment]
ReadTheDocs is now set up and can be viewed at https://acesloris.readthedocs.io/en/latest/.

We are still in the process of updating existing, archived Wiki files to the repository.

**Comment by johnsaigle** [comment]
I'm going to close this issue because it lacks precision. This project is well underway and we aren't likely to forget about it. There is also a Project associated with this so we will have a record.
