### ISSUE TITLE
Google Summer of Code: Improve Automated Testing 

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#4423]
As example tasks for our [Google Summer of Code project](https://www.incf.org/gsoc2019/projectlist#LORIS), hosted in coordination with [INCF.org]()

Expand coverage / tests for existing unit tests : 
- [x] Candidate class

Write a unit test in PHP for any of these *.class.inc files (found in `php/libraries/`) 

"Easy" (1 day for a senior testing dev)  
- [x]     Breadcrumb.class.inc
- [x]    BreadcrumbTrail.class.inc
- [ ]    Identifier.class.inc

"Difficult" (2 days for a senior testing dev)  
- [x]  NDB_Config.class.inc
- [ ] NDB_Caller.class.inc
- [x] NDB_Page.class.inc.

Notes: 
* For examples, see pull request #4378 and files under `test/unittests/`
* Commit your PHP test file under `test/unittests/`
* To install your own Loris on your own computer (or VirtualBox or VMWare .... any platform you like) :   Se this repo's Readme and  [Wiki install guide](https://github.com/aces/Loris/wiki/Installing-Loris)

**Comment by johnsaigle** [comment]
For an example of what to do, see pull request #4378.

**Comment by johnsaigle** [comment]
@AlexandraLivadas re: today's meeting -- have you taken a look at this? Shen prepared it as a path to getting started with the development of our unit tests.

**Comment by johnsaigle** [comment]
AH sorry just saw your Breadcrumb PRs.

**Comment by AlexandraLivadas** [comment]
**Updated To-Do List after July 30th meeting:**

Merged PRs:
- #4988 -- Visit.class.inc, VisitController.class.inc
- #4840 -- BreadcrumbTrail.class.inc
- #4769 -- Breadcrumb.class.inc

Open PRs to Complete:
- [ ] #4987 -- Settings.class.inc 
- [ ] #4979 -- User.class.inc 
- [ ] #4936 -- Candidate.class.inc
- [ ] #4916 -- LorisForm.class.inc
- [ ] #4861 -- Utility.class.inc

Classes to Tackle:
- [ ] NDB_Config
- [ ] NDB_Caller
- [ ] NDB_Page

**Comment by christinerogers** [comment]
Related PRs/issues:
* #4497 - attempt at code coverage pre/post GSOC

**Comment by christinerogers** [comment]
Correction: @kongtiaowang  covered most of NDB_Config in the spring   #4383 

- [ ] 2 functions in NDB_Config are still missing tests: `checkMenuPermission()` and `getMenuTabs()`  -> @AlexandraLivadas

**Comment by christinerogers** [comment]
@AlexandraLivadas  to update this issue with "Last Day status: August 23" -- all testing PRs

**Comment by AlexandraLivadas** [comment]
**Last Day Status: August 23**

Merged Testing PRs:

1. #4769 -- Breadcrumb.class.inc
2. #4840 -- BreadcrumbTrail.class.inc
3. #4861 -- Utility.class.inc
4. #4916 -- LorisForm.class.inc
5. #4936 -- Candidate.class.inc
6. #4979 -- User.class.inc
7. #4987 -- Settings.class.inc
8. #4988 -- Visit.class.inc, VisitController.class.inc
9. #5012 -- NDB_Config.class.inc

Other (mostly documentation related) Merged PRs:
1. #4622 -- test_instruments Readme
2. #4649 -- installdb.php script
3. #5020 -- Test set-up Readme

Open PRs:

- [ ] #5024 -- NDB_Page.class.inc: This is being reviewed now. All tests have been written.
- [ ] #5066 -- Markdown of Unit Testing Guide
