### ISSUE TITLE
Post-release 21 Documentation updates

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#4995]
(non-exhaustive list, in progress) 
Needs cross-checking with new [Readmes from Wiki-revamp](https://github.com/aces/Loris/pull/4093)

### Things moved under docs/ RaisinBread -> broken links 

*  public instruments removed / moved to Raisinbread
- [ ]  bmi.linst which used to be [under docs/instruments/](https://github.com/aces/Loris/tree/20.3-release/docs/instruments)
- [ ] MRI Parameter form which is required(?) for the upcoming QC Browser (can't load without)

- [ ] requires updating the Behavioural Setup Guide... probably other pages too.
* readmes : e.g. https://github.com/aces/Loris/blob/master/LORIS_react.README.md
- [x] #5392 broken links in Contributing.md, 
- [x] several wiki pages
- [ ] other places in the Repo

### Install process Readme(s): 

- [x] #5197 Makefile needs to be run for fresh installs. not composer (? TBC) : add to Readmes, wiki
- [x] #5017 NodeJS version matters (PR sent for main readme only)
- [x] #5018  CentOS 21.0.0 specific updates (including NodeJS)

### Reliability module removed :  Remove all mentions #4596
- [x] Code: [statistics/js/form_stats_reliability.js](https://github.com/aces/Loris/blob/21.0-release/modules/statistics/js/form_stats_reliability.js) still exists (technically this is Stats module code cleanup, not Reliability module 
- [x] config.xml #5433

### Training module removed  - Documentation to be updated: 
- [x] [Examiner module readme](https://github.com/aces/Loris/tree/21.0-release/modules/examiner) : remove mentions of Training module

### Reactified modules: 

- [x] #5410 Remove [mentions of "Show data"  button](https://github.com/aces/Loris/search?q=%22Show+data%22&unscoped_q=%22Show+data%22) if no longer relevant 
e.g. [15 markdown files](https://github.com/aces/Loris/search?l=Markdown&q=%22Show+data%22) files including: 
- [x] Imaging Browser Help text
- [ ] (very minor) [5 Test plans to be updated](https://github.com/aces/Loris/search?q=%22Show+data%22+test_plan&unscoped_q=%22Show+data%22+test_plan) 

### Tools scripts moved to a different directory
- [ ] Wiki / wiki-readmes to be updated

### CenterID -> Registration Center ID  #4078

- [ ] [wiki](https://github.com/aces/Loris/search?q=CenterID&type=Wikis) / wiki readmes
- [ ] Module Readmes
- [ ] installers for Loris, Loris-MRI 
- [ ] Loris-MRI documentation 
- [ ] any scripts? any help text? 

### Gender renamed to sex 
- [ ] Wiki / Wiki-readmes to be updated
- [x] search help text
- [x] search module readmes (unlikely) 
- [x] in the Codebase #5874 (local variable names, e.g.)
- [ ] API release - because it was stable, [per Dave's 5874 comment](https://github.com/aces/Loris/pull/5874#discussion_r359480895)

### Config Path cleanup: #4314 
Double-check the wiki, etc. 

### UseProjects - remove all mentions killed #4496
- [x] 1 case in [wiki](https://github.com/aces/Loris/search?q=useProject&type=Wikis)

**Comment by johnsaigle** [comment]
Last point should be addressed by #5433

**Comment by johnsaigle** [comment]
>Training module removed - update Module Readmes:
 Examiner module readme : remove mentions of Training module

@sruthymathew123 Would you be able to update this during release testing for v22?

**Comment by johnsaigle** [comment]
> Gender renamed to sex

All points resolved by #5874 except for GitHub wiki files.

**Comment by johnsaigle** [comment]
@christinerogers I think this is resolved except for the RegistrationCenterID references in the (deprecated) wiki. 

Are you in favour of closing this and creating a separate ticket for this final update?

**Comment by johnsaigle** [comment]
I'm going to close this for now. The remaining items exist in the GitHub Wiki which is in the process of being deprecated. As we rewrite these pages for the new ReadTheDocs wiki we should be able to catch outdated sections during code review.
