### ISSUE TITLE
[dataquery, surveyaccounts] Fix/restore module Readmes

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5196]
PR #3437 erroneously moved 2 module specs under the help directory.
To correct: 
* dataquery 
- [x] modules/dataquery/help/dataquery.md should be moved(&renamed) modules/dataquery/README.md - see #5206 
- [x] Restore the old Help text (and check for updates) - see #3390 for modules/dataquery/help/dataquery.md (PR sent: #5200)

* survey accounts
- [x]  Remove [modules/survey_accounts/help/survey_accounts.md](https://github.com/aces/Loris/blob/minor/modules/survey_accounts/help/survey_accounts.md) - it's a copy of the existing module spec and shouldn't exist in 2 places. (PR sent: #5207) - see #5221 which fixes the issue and has been MERGED.

**Comment by christinerogers** [comment]
@knoll-alex Could you update the top description of this issue anytime Wednesday? thanks!

**Comment by christinerogers** [comment]
closing this issue because the PRs are likely to get merged in the next week. 👍
