### ISSUE TITLE
[InstallDocs] Add Install markdowns to 23 branch 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6475]
Given that we are releasing the install markdowns as part of the 23 release -- 
Steps: 
- [x] copy from `master` to 23 branch - Ubuntu and CentOS instructions 
- [ ] move/rename ready files from `wiki/` path (per Loris mtg may05)
- [x] also do #6415 - remove spaces from filenames
- [x] update the curl dependency in the ubuntu markdowns per #6492
- [x] Include #6181 changes on this branch ([per this comment by johnsaigle](https://github.com/aces/Loris/pull/6181#issuecomment-628291312))

**Comment by johnsaigle** [comment]
>  move/rename ready files from wiki/ path (per Loris mtg may05)

I think the consensus was to copy the install files or else create symlinks to the two install files under `docs/wiki/...`. The names and content of the original files should not be modified. (Modifying spaces within the filenames is OK.)

**Comment by christinerogers** [comment]
updating description of this issue to include @johnsaigle 's note re including #6181 changes on 23.
