### ISSUE TITLE
[Manual Testing] acknowledgements 

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#7572]
# Module Name: acknowledgements

## Tasks:
- [ ] Review issues from previous release testing

### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
 - [ ] No ajax dir
 - [ ] Data framework
 - [ ] React
 - [ ] Widgets (at least 1 for candidate to show up in candidate profile)

## Related Issues
https://github.com/aces/Loris/issues/6231
https://github.com/aces/Loris/issues/6681
https://github.com/aces/Loris/issues/7659
https://github.com/aces/Loris/issues/7659

## Comments
- `htdocs/acknowledgements/acknowledgements.php` still exists...
- Not clear how to use this module. Help text and `Readme.md` need an update.
- Issues from previous testing round still there, except for the issue related to the automated tests.
