### ISSUE TITLE
[Manual Testing] candidate_list

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#7574]
## Tasks:
- [x] Review issues from previous release testing

### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)

### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [ ] Make sure RB is complete

### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - https://github.com/aces/Loris/issues/7093
 - https://github.com/aces/Loris/issues/7608
 - https://github.com/aces/Loris/issues/7609
 - https://github.com/aces/Loris/issues/7612
 - https://github.com/aces/Loris/issues/7644
 - https://github.com/aces/Loris/pull/7610

## Comments

README and TestPlan were out of date and needed a lot of updates

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
