### ISSUE TITLE
[Manual Testing] datadict

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#7575]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans https://github.com/aces/Loris/pull/7647
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …) https://github.com/aces/Loris/pull/7647
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date https://github.com/aces/Loris/issues/7648
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
https://github.com/aces/Loris/issues/7645, https://github.com/aces/Loris/issues/7648

## Comments
 - haven't tested item 10. of the test plan yet because need back-end access
 - Testing not done for the beta data dict
 - Issue #7645 gone. Issue #7648 still there.

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by suzanne-lee** [comment]
Tested the module and everything works with the exception of the issue already described by Zaliqa (https://github.com/aces/Loris/issues/7645), which has an open PR addressing it (https://github.com/aces/Loris/pull/7853)
