### ISSUE TITLE
[Manual Testing] instrument_builder

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7576]
## Tasks:
- [ ] Review issues from previous release testing

### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)--> There is a Templates Directory.  
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues

MINOR: 
* #7611

Previously reported bugs still outstanding: 
* #7526

## Comments
 ❓  wasn't there supposed to be a Radio element since 2020? #5846.  (no sign of a radio in any docs or the module front-end)
From Round 2:
I found some issues:

when the Question Name is redundant, the related error stays there as the user changes the field, even changing the question type does not change the error message
There is no not_answered option for Text Area (Step 1.e.2 in [Text Plan](https://github.com/xlecours/Loris/blob/8c2fdb49c82e7b03a2ed66861066a6b312aaad42/modules/instrument_builder/test/TestPlan.md))
There is typo in the test plan (linst)

## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by miladheshmati** [comment]
I found some issues:

- when the Question Name is redundant, the related error stays there as the user changes the field, even changing the question type does not change the error message
- There is no not_answered option for Text Area (Step 1.e.2 in [Text Plan](https://github.com/xlecours/Loris/blob/8c2fdb49c82e7b03a2ed66861066a6b312aaad42/modules/instrument_builder/test/TestPlan.md))
- There is typo in the test plan (linst)

**Comment by kongtiaowang** [comment]
done
