### ISSUE TITLE
[Manual Testing] DQT

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7578]
## Tasks:
- [x] Review issues from previous release testing

### Documentation Tasks
 - [ ] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**
 - https://github.com/aces/Loris/issues/7670
 - https://github.com/aces/Loris/issues/7683
 - https://github.com/aces/Loris/issues/7684
 - https://github.com/aces/Loris/issues/7685
 - https://github.com/aces/Loris/issues/5071
- https://github.com/aces/Loris/issues/5111
- https://github.com/aces/Loris/issues/5114 (Beginner Friendly; UI)
- https://github.com/aces/Loris/issues/5124
- https://github.com/aces/Loris/issues/6751
- https://github.com/aces/Loris/issues/6566
- https://github.com/aces/Loris/issues/6583 (UI)
- https://github.com/aces/Loris/issues/6596 (404 issue appears to have been previously resolved; delayed display still an issue)
- https://github.com/aces/Loris/issues/6845
- https://github.com/aces/Loris/issues/7287

new:
- https://github.com/aces/Loris/issues/7935
- https://github.com/aces/Loris/issues/7936
- https://github.com/aces/Loris/issues/7938
- https://github.com/aces/Loris/issues/7939

Round #3 issue:
- https://github.com/aces/Loris/issues/8009
- https://github.com/aces/Loris/issues/8010
## Comments
- Unable to test filter combinations, enum filters are broken

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
