### ISSUE TITLE
[Manual Testing] MRI Violations

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7581]
## Tasks:
- [x] Review issues from previous release testing

### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory) - _there is a templates/ directory_
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
New issue: **Dashboard widget broken** https://github.com/aces/Loris/issues/7920

Old issues still valid: 
 - No help text for subpage: 5714 (Help text missing for subpages)
 - still an issue: https://github.com/aces/Loris/issues/7681
 - 

- https://github.com/aces/Loris/issues/5166 (Filter values not set properly)
- https://github.com/aces/Loris/issues/5714 (Help text missing for subpages)
- https://github.com/aces/Loris/issues/6576 (Proposal; Standardize contents of 'Problem' dropdowns)
- https://github.com/aces/Loris/issues/6982 (Remove link to MRI violations)
- https://github.com/aces/Loris/issues/7203 (Scrolling issue)
- https://github.com/aces/Loris/issues/7449 (Reactification)
- https://github.com/aces/Loris/issues/7472 (Can't resolve for scan with multiple violations)
- https://github.com/aces/Loris/pull/7473 (Reactification)
## Comments
 - **insert comments here**
- All other issues found have been previously described and have active tickets issued as listed above.

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by christinerogers** [comment]
Reproduced Santiago's bug found.  @ridz1208 does this mean it's not a Fail, or a double Fail ?
