### ISSUE TITLE
[Manual Testing] Candidate profile

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#7587]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**
#7643 
#7652 
#7696 
 - **Candidate Release testing**
https://github.com/aces/Loris/issues/8040
## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by kongtiaowang** [comment]
[Candidate_profile] instrument link not working #7652

**Comment by kongtiaowang** [comment]
This is a new issue of CCNA 24. 
https://github.com/aces/Loris/issues/8042

**Comment by kongtiaowang** [comment]
done
