### ISSUE TITLE
[Manual Testing] create_timepoint

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#7604]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - #7602
 - #7603
 - https://github.com/aces/Loris/issues/8017

## Comments
 -  I did not check that raisinbread data is complete because for testing sake I think there should be a subproject that does not have any visits linked to it in the Config.xml file (satisfies part of step 4 of TestPlan). This is currently not the case
 - Widgets box checked even though there are no widgets because widgets are not necessary for this module

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
