### ISSUE TITLE
[Manual Testing] my_preferences

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7605]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues

#7706 basic data entry user can't turn notifications on and off.   
and also : 
#7704 - user can see notification settings (which are on) for modules they can't access
#7705 - notifications not working as expected

## Comments

I think these aren't critical to the release, but is a weakness in the My Preferences module, and the Notifications features. 
Permissions interactions should definitely have been noted in this Readme when this Notifications settings feature was added to loris. 

LORIS V24 testing: issues #7704 and #7706 still present.
 
## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
