### ISSUE TITLE
[Manual Testing] battery_manager

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#7606]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - #7687 
 - #7694 
 - #7697 
 - https://github.com/aces/Loris/issues/7798

## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by ridz1208** [comment]
@nicolasbrossard I just added https://github.com/aces/Loris/issues/7798 to this ticket, can you confirm you are getting the same error? if this usecase was not already i nthe test plan please add it

**Comment by suzanne-lee** [comment]
Reported issues https://github.com/aces/Loris/issues/7697 and https://github.com/aces/Loris/issues/7798 have been addressed and resolved. The outstanding issue https://github.com/aces/Loris/issues/7694 hasn't been addressed yet.
