### ISSUE TITLE
[Manual Testing] issue_tracker

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#7616]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end) - needs updating
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
**list related issues/bugs here**
 - https://github.com/aces/Loris/issues/7887
 - https://github.com/aces/Loris/issues/7884
 - https://github.com/aces/Loris/issues/7883
 - https://github.com/aces/Loris/issues/7882
 - https://github.com/aces/Loris/issues/7881
 -  https://github.com/aces/Loris/issues/7618#issue-1009744603
Round 3 issues:
- https://github.com/aces/Loris/issues/8003
- https://github.com/aces/Loris/issues/8004
- https://github.com/aces/Loris/issues/8005
- https://github.com/aces/Loris/issues/8006
- https://github.com/aces/Loris/issues/8007
- https://github.com/aces/Loris/issues/8008
## Comments
 - **insert comments here**
From Round 1: Tried to create a new account for myself but got an error, so continued using Admin to test

Round 3 comments:

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by LeighMac** [comment]
Tried to create a new account for myself but got an error, so continued using Admin to test
![Screen Shot 2021-09-28 at 9 00 00 AM](https://user-images.githubusercontent.com/9272886/135093699-5c777bfb-d352-4672-88ef-c9d13ca721e5.png)
