### ISSUE TITLE
[Manual Testing] next_stage

### ISSUE THREAD

**Issue by jstirling91** [aces/Loris#7617]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - [Test Case 8] #7872 
 - #7871 - User help text

## Comments
 - Module contains no help text

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by kongtiaowang** [comment]
https://github.com/aces/Loris/pull/7923(missing help content for next_stage) is open.

**Comment by kongtiaowang** [comment]
done
