### ISSUE TITLE
[Manual Testing] DICOM_archive

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#7622]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - #7620
 - #7621
 - Issues from last testing round still open: #6981 #6982

## Comments
 - Template directory exists, no Widgets

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by LeighMac** [comment]
Apologies, I can not do some of these, it is beyond my knowledge level. However, the DCM Archive has passed manual testing. I think what could be helpful in the Help Section is to give examples of what questions can be answered (ie: workflow examples) that you would use this module for instead of say MRI Violations
