### ISSUE TITLE
[Manual Testing] imaging_qc

### ISSUE THREAD

**Issue by shonibare** [aces/Loris#7627]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**
 - round 1, not reproducible https://github.com/aces/Loris/issues/7625
- round 2: https://github.com/aces/Loris/issues/7879

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
