### ISSUE TITLE
[Manual Testing] Publication

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#7629]
## Tasks:
- [x] Review issues from previous release testing
 
### Documentation Tasks
- [ ]  Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)

### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
    - https://github.com/aces/Loris/issues/7637
 - [x] Make sure RB is complete
    - https://github.com/aces/Loris/issues/7636

### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)
## new issue
- https://github.com/aces/Loris/issues/8029

## Issues
 - https://github.com/aces/Loris/issues/7880
 - https://github.com/aces/Loris/issues/7878  
 - https://github.com/aces/Loris/issues/7877
 - https://github.com/aces/Loris/issues/7401
  - https://github.com/aces/Loris/issues/7280
  - https://github.com/aces/Loris/issues/7007
  - https://github.com/aces/Loris/issues/7006
  - https://github.com/aces/Loris/issues/7005

## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by shonibare** [comment]
The module was tested as instructed and all the tests passed. Closing this issue.
