### ISSUE TITLE
[Manual Testing] survey_accounts

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#7633]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
Issues with the module itself:
 - https://github.com/aces/Loris/issues/7668
 - https://github.com/aces/Loris/issues/7672
 - https://github.com/aces/Loris/issues/7918
- https://github.com/aces/Loris/issues/8041
Issues with the surveys:
 - https://github.com/aces/Loris/issues/7667
 -  https://github.com/aces/Loris/issues/7673
 - https://github.com/aces/Loris/issues/7675
New Issues:
- https://github.com/aces/Loris/issues/8020
- https://github.com/aces/Loris/issues/8021
- https://github.com/aces/Loris/issues/8022

## Comments
 - The ajax and templates directory still exist
 - The help menu text contains HTML `<br>` tags 

## Status
 - [ ] Testing COMPLETE
 - [x] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by suzanne-lee** [comment]
Couldn't test what happens after completing a survey (such as checking if status = complete), as there were bugs with both the BMI and Med Hist that prevented me from submitting those.

**Comment by driusan** [comment]
@suzanne-lee were the bugs resolved for the next testing round?

**Comment by suzanne-lee** [comment]
The following issue was resolved: #7668

I don't think the others were resolved.

**Comment by SantiagoTG** [comment]
Similar to previous testing round, can't check for completion of a survey as I can't submit or even save progress of survey.
