### ISSUE TITLE
[Manual Testing] Imaging Browser

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#7640]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [x] Data framework implemented
 - [ ] React (no templates directory)
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**
https://github.com/aces/Loris/issues/7563
https://github.com/aces/Loris/issues/7873

## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
