### ISSUE TITLE
[Manual Testing] configuration

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#7660]
## Tasks:
- [x] Review issues from previous release testing
  
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete

### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - https://github.com/aces/Loris/issues/7691
 - #7947 
 - #7948
 - https://github.com/aces/Loris/issues/5132
 - https://github.com/aces/Loris/issues/7134
## Comments
 - **insert comments here**
     - It doesn't make sense to ask to test manually each and every configs when there is no documentation about them. I don't know what half of the configs are for and what is the expected behaviour. And even if docs were available. It would take more than 60 hours to test everything manually.
## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by xlecours** [comment]
This is untestable within the time window allocated to testing v.24

**Comment by xlecours** [comment]
TODO

- [ ] Update testPlan
- [ ] Update Automated tests

@xlecours to create issues

**Comment by ridz1208** [comment]
@xlecours have you done your TODO ?

**Comment by xlecours** [comment]
@ridz1208  
- testplan updates : https://github.com/aces/Loris/issues/7660
- Update Automated tests: no.  testAllLinks() is still missing the last 5 "links".

**Comment by ridz1208** [comment]
@ridz1208 I obviously did not test every single combination, i limited myself to a sample from each page and at least every type
