### ISSUE TITLE
[Manual Testing] examiner

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#7720]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
**_First round_**
 - https://github.com/aces/Loris/issues/7721

**_Second round_**
 - #7888
 - https://github.com/aces/Loris/issues/7965

**_Third round_**
- https://github.com/aces/Loris/issues/8026

## Comments
 - **insert comments here**

## Status
 - [ ] Testing COMPLETE
 - [x] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
