### ISSUE TITLE
[Manual Testing] Statistics

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7779]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**
New Issues:
https://github.com/aces/Loris/issues/8027
https://github.com/aces/Loris/issues/8028
Old issues:
#7839 
## Comments
 - **insert comments here**
Could not test the module further because of the 500 error
## Status
 - [ ] Testing COMPLETE
 - [x] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by charliehenrib** [comment]
@ridz1208 There is no more data entry permission and Access Profile: View/Create Candidates and Timepoints - Own Sites does not grant access to the module. 

Update the test plan and I will retest.

**Comment by ridz1208** [comment]
@charliehenrib my tests say it's working fine

**Comment by jftunteng** [comment]
> @ridz1208 There is no more data entry permission and Access Profile: View/Create Candidates and Timepoints - Own Sites does not grant access to the module.
> 
> Update the test plan and I will retest.

I'm able to access Statistics with Access Profile: View/Create Candidates and Timepoints - Own Sites, but there's no Data Entry permission on my end

**Comment by jftunteng** [comment]
Behavioural Statistics 
* View Details link does not work in Data Entry Statistics Table

Imaging Statistics 
* Changing the breakdowns does not adjust the table
* 0% is shown for each breakdown across all sites and visits

**Comment by zaliqarosli** [comment]
@cmadjar @ridz1208 am i supposed to be assigned to this? in the email, this module was assigned to xavier!
