### ISSUE TITLE
[Manual Testing] help_editor

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7780]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - #6940
 - #6968
 - #8015

## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by charliehenrib** [comment]
- [ ] The READ ME file and test plan should be updated to permission: Help Editor: Edit Help documentation
- [ ] Step 7 in the test plan is not working. Seems to be an existing [issue](https://github.com/aces/Loris/issues/6940)
- [ ] Step 8 in the test plan is not working. Seems to be an existing [issue](https://github.com/aces/Loris/issues/6940)
- [ ] The edit help content is not working

**Comment by cmadjar** [comment]
The same issues as raised in previous testing round are still open issues and therefore bugs present in the help editor module. I added an extra issue for another button not working: #8015
