### ISSUE TITLE
[Manual Testing] data_release

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7782]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [x] React (no templates directory)
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 -  #7894
 - #8023 
 - #8024
 - #8025

## Status
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
 - [x] Testing COMPLETE

**Comment by ridz1208** [comment]
@CamilleBeau Isuggest retesting the module.

This code doesn't look right https://github.com/aces/Loris/blob/main/modules/data_release/php/permissions.class.inc#L151

**Comment by AlexandraLivadas** [comment]
> @CamilleBeau I suggest re-testing the module.
> 
> This code doesn't look right https://github.com/aces/Loris/blob/main/modules/data_release/php/permissions.class.inc#L151

@ridz1208 I think this explains the issue I have raised: #8023

**Comment by ridz1208** [comment]
@AlexandraLivadas I knew it !!!

@CamilleBeau just ignored me
