### ISSUE TITLE
[Manual Testing] instrument_manager

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7783]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …) 
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
- https://github.com/aces/Loris/issues/7903
- https://github.com/aces/Loris/issues/7904
-https://github.com/aces/Loris/pull/7901
## Comments
 - did not test items 3 and 8 because of limited access to test VM. Can do this though if needed.
 - was not able to successfully add an instrument - got 500 upon upload, and 409/404 everytime I tried to re-upload a previously failed instrument

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
