### ISSUE TITLE
[Manual Testing] API

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7784]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - #7916 
               - PUT/PATCH request `/candidates/{candid}/{visit}/instruments/{instrument}/flags` not correctly updating flags
               - PUT/PATCH request `/candidates/{candid}/{visit}/instruments/{instrument}/dde/flags` not correctly updating flags
 - #7917 
               - PUT request `/candidates/{candid}/{visit}/images/{filename}/qc` not updating image's qc values

## Status
 - [ ] Testing COMPLETE
 - [x] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
**Could not test recordings endpoints**

**Comment by ridz1208** [comment]
@AlexandraLivadas Both you and @samirdas will be testing this one (good luck!)

You can always use the `api_docs` module to help with testing

**Comment by AlexandraLivadas** [comment]
Could not test recordings endpoints because there is no data on CCNA-DEV
