### ISSUE TITLE
[Manual Testing] electrophysiology_browser

### ISSUE THREAD

**Issue by driusan** [aces/Loris#7859]
## Tasks:
- [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - #7890
 - #7891

## Comments
 - **insert comments here**

## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [x] Could Not Test (please specify reasons in comment)

**Comment by driusan** [comment]
@CamilleBeau There was no first round testing ticket for this, when the assignments go out can you make sure you also complete the "Standards: Make sure the latest standards are upheld" section?

**Comment by CamilleBeau** [comment]
> @CamilleBeau There was no first round testing ticket for this, when the assignments go out can you make sure you also complete the "Standards: Make sure the latest standards are upheld" section?

Yes will do!

**Comment by jesscall** [comment]
Could not test on CCNA-DEV because there is no data !
