### ISSUE TITLE
[Issue Tracker] Feature proposals - Summary ticket

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#8328]
Linking in one place the various feature proposals for the Issue Tracker and current progress on some of these suggestions:

- [ ] Make attachment visible
- [ ] Assignee should not be required when creating a new issue
- [ ] Add ‘instrument’ preferably from a drop down of all instruments
- [ ] Add more granular permissions (i.e. See/Comment/Edit own issues, See/Comment/Edit own site issues, See/Comment/Edit all issues, Close own issues, Close own site issues, Close all issues)
- [ ] Add option for ‘All’ under sites (when issue is not site specific) when creating a new issue
- [ ] Make ‘watcher’ reactified or searchable or at very least alphabetical when creating a new issue
- [ ] Enter a Ticket from within an instrument form
- [ ] Build "Related issues" algorithm

**Related to:**
- https://github.com/aces/Loris/issues/4150
- https://github.com/aces/Loris/issues/4818
- https://github.com/aces/Loris/issues/5172
- https://github.com/aces/Loris/issues/5173
- https://github.com/aces/Loris/issues/8005

**Comment by xlecours** [comment]
@SantiagoTG Can you update this ticket with what is done and not please?

**Comment by SantiagoTG** [comment]
Above items that have been done are checked along with the corresponding PR where available. Below are pending items along with a few new entries:

- [ ] Add ‘instrument’ preferably from a drop down of all instruments - https://github.com/aces/Loris/issues/8896
- [ ] Add more granular permissions - https://github.com/aces/Loris/issues/8897
- [ ] Make ‘watcher’ reactified / searchable 
- [ ] Enter a Ticket from within an instrument form
- [ ] Build "Related issues" algorithm
- [ ] Automatically specify Assignee/Watcher based on Category - https://github.com/aces/Loris/issues/8898
- [ ] Automatically specify default Assignee/Watcher based on Site - https://github.com/aces/Loris/issues/8899

**Related to:**
- https://github.com/aces/Loris/issues/5172
- https://github.com/aces/Loris/issues/5173
