### ISSUE TITLE
brainbrowser

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8493]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues and PRs
List related issues/bugs here
- https://github.com/aces/Loris/pull/8561
- https://github.com/aces/Loris/pull/8335
- https://github.com/aces/Loris/issues/8562

**Minor Issues:**

**Previously reported bugs still outstanding:** 
- [ ]  https://github.com/aces/Loris/issues/8016 
- [ ]  https://github.com/aces/Loris/issues/7681

## Comments
 - [ ] Testing COMPLETE
 - [x] Partially Tested
 - [x] Could Not Test (please specify reasons in comment) (See #8558)
