### ISSUE TITLE
publication

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8500]
## Tasks:
- [ ] Review issues from previous testing
### Documentation Tasks
 - [ ] Update test plans
 - [x] Review/update module READMEs
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Open the web console and make sure no JS or network error shows up during testing. Create an issue reporting them if any.
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues

#8825
#8826

## Comments
Could not fully test as module is not loading properly.

## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [x] Could Not Test (please specify reasons)

**Comment by aarushichaudhry** [comment]
# Tasks:
- [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**


## Comments
 - **insert comments here**


## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by aarushichaudhry** [comment]
Assigning to Nic as per https://docs.google.com/spreadsheets/d/12ygDc_JUnqMfnqrcdFWURJdyDON47IqbzW-qVhjB2Xk/edit#gid=1149300992
