### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8502]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
All issues solved (left below for reference)
 -  (https://github.com/aces/Loris/issues/8585)
 -  (https://github.com/aces/Loris/issues/8586)

## Comments
 - Did not yet do testing with involves checking the DB
 - seems like ‘study progression — site scans’ in the dashboard could be out of step with the scans per site in statistics, but I could be wrong and Im having a hard time checking

## Status
 - [ ] Testing COMPLETE
 - [x] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by KLaFleur** [comment]
## Tasks:
- [ x] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 -  https://github.com/aces/Loris/issues/8585
 -  https://github.com/aces/Loris/issues/8586


## Comments
 - Did not yet do testing with involves checking the DB
 - seems like ‘study progression — site scans’ in the dashboard is out of step with the scans per site in statistics, but I could be wrong and Im having a hard time checking
 - unable to create candidate (and therefore do full testing) because the date field would not allow me to include the day of the month
 - 


## Status
 - [ ] Testing COMPLETE
 - [ x] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by sruthymathew123** [comment]
Testing this one for Candidate Release
