### ISSUE TITLE
dicom_archive

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8503]
## Tasks:
- [x] Review issues from previous release testing

### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
   - need to update it, few things missing (permissions)
 - [x] Check user help content for accuracy and formatting (front end)
   - need to re-check when the help format bug is resolved
 
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up-to-date - `seems ok but need to run them`
 - [x] Make sure RB is complete
   
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
   - main php class should `extends \DataFrameworkMenu`
 - [ ] React (no templates directory)
   - `there is one`
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues

 - new issues:
   - #8705
   - #8554
   - #8610 

 - Issues from last testing round still open: 
   - #6981 
   - #6982
   - #6658
   - #4558 (stale -> first comment from `21.0 testing`)

## Comments
 - Template directory exists, no Widgets

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by regisoc** [comment]
## Tasks:
- [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - #7620
 - #7621
 - Issues from last testing round still open: #6981 #6982

## Comments
 - Template directory exists, no Widgets

## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by miladheshmati** [comment]
Tested and no issue found
