### ISSUE TITLE
imaging_uploader

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8504]
## Tasks:
- [x] Review issues from previous release testing

### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)

### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date - `seems ok but need to run them`
 - [x] Make sure RB is complete
 - [x] phase 2 (?):
   - backend access: make sure the `visit label` in the `browse` tab reflects the `Visit_label column in the session table for any Active candidate`.
   - Test upload with `Phantom = No` with:
     - A candidate that has `Active set to 'N'` in the `candidate` table
     - A session that has `Active set to 'N'` in the `session` table

### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
   - has ajax dir
 - [ ] Data framework implemented
   - main class `extends \NDB_Menu_Filter_Form`
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues

**Newly reported issues**
- #8623 
- #8609
- #8665
- #8666
- #8707

**Previously reported issues (that are still relevant)**
- #6621
- #7719 
- #6873 
- #4920 (some modifications on UI, but stale issue)
- #5163 (stale)
- #4750 (stale)
- #5048 
- #5046 (stale, issue is resolved. However, listed here because the process order could be better. This issue is still relevant, but a new issue should be raised instead. Process order right now = upload the file THEN look for the file size, which could take a long time)
- #4011 (stale, doc missing, e.g. config `MriConfigFile`: can find Config changes but no doc on LORIS or LORIS-MRI repo)
- #3022 (stale, API for data upload?)

**Candidate release testing issues**

- https://github.com/aces/Loris/issues/8803
- https://github.com/aces/Loris/issues/8807
- https://github.com/aces/Loris/issues/8812
- https://github.com/aces/Loris/issues/8822
- https://github.com/aces/Loris/issues/8823

## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by regisoc** [comment]
## Tasks:
- [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
**Previously reported issues (that are still relevant)**
- #6621

**Newly reported issues**
- #7634


## Comments
 - **insert comments here**

## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by sruthymathew123** [comment]
Hi @zaliqarosli, I couldn't test this module completely as it requires a valid scan. Backend access and loris-mri pipeline set up needed to test things mentioned from Step 6 onwards. Let me know if you can have a look or something I can do to complete testing.

**Comment by zaliqarosli** [comment]
@sruthymathew123 can you complete the tasks in the description of this issue above and i'll test items 6-23 in the test plab

**Comment by sruthymathew123** [comment]
@zaliqarosli  Sorry for the late update here. I tested upto 6 during the testing round.

**Comment by zaliqarosli** [comment]
hi @sruthymathew123 please review the tasks list in the description on this issue and complete them. there are some checkboxes that haven't been ticked. i.e. you can still do 1. "Review/update module READMEs (Interactions, configurations, permissions, widgets, …)" and 2. "Check user help content for accuracy and formatting (front end)". and do the rest
<img width="1004" alt="Screenshot 2023-06-21 at 11 09 44 AM" src="https://github.com/aces/Loris/assets/17415878/570d7ff5-ddfc-4482-bb6d-421bd2af1218">
