### ISSUE TITLE
electrophysiology_uploader

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8509]
## Tasks:
- [x] Review issues from previous release testing

### Documentation Tasks
 - [x] Update test plans 
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end) => https://github.com/aces/Loris/issues/8597

### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up-to-date => https://github.com/aces/Loris/issues/8599
 - [ ] Make sure RB is complete => https://github.com/aces/Loris/issues/8600

### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)
    - note sure if there should be a widget for this module... 

## Issues

**Newly reported issues**
- https://github.com/aces/Loris/issues/8597
- https://github.com/aces/Loris/issues/8599
- https://github.com/aces/Loris/issues/8600
- https://github.com/aces/Loris/issues/8603
- https://github.com/aces/Loris/issues/8604
- https://github.com/aces/Loris/issues/8605

## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
