### ISSUE TITLE
imaging_qc

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8510]
## Tasks:
- [x] Review issues from previous release testing

### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end) -> should be checked again after #8545 fix is integrated

### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up-to-date
   - only automated test is page permission (updated 3y ago). 
 - [x] Make sure RB is complete

### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
   - no framework, main class extends `\NDB_Menu_Filter`
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
**Previously reported issues (that are still relevant)**
- #6591 
- #5325 (stale, seems resolved, can close? - caveat added in the imaging_qc module README for v22)

**Newly reported issues**
- #8607
- #8608

## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
