### ISSUE TITLE
electrophysiology_browser

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8513]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
- #8690 
- #8691 

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by ridz1208** [comment]
waiting on https://github.com/aces/Loris/pull/8415

**Comment by jeffersoncasimir** [comment]
## Round 2 Tasks:
- [x] Review issues from previous testing
### Documentation Tasks
 - [x ] Update test plans
 - [x] Review/update module READMEs
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Open the web console and make sure no JS or network error shows up during testing. Create an issue reporting them if any.
 - [x] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date (TODO)
 - [x] Make sure RB is complete
### Standards: Make sure the latest are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
No new issues

## Comments
Outstanding from Round 1:
 - #8690
 - #8691


## Status
 - [ ] Testing COMPLETE
 - [x] Partially Tested
 - [ ] Could Not Test (please specify reasons)
