### ISSUE TITLE
candidate_profile

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8517]
## Tasks:
- [x] Review issues from previous release testing
https://github.com/aces/Loris/issues/7679
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
https://github.com/aces/Loris/issues/8545
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete ***This module has no RB as it uses widgets and API**
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**
https://github.com/aces/Loris/issues/7679
https://github.com/aces/Loris/issues/8568
https://github.com/aces/Loris/issues/8583
https://github.com/aces/Loris/issues/8584

- **Second Round Testing**
https://github.com/aces/Loris/issues/8709
https://github.com/aces/Loris/issues/8710

 - **Candidate Release testing**

## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by zaliqarosli** [comment]
@driusan should candidate_profile permissions work exactly like timepoint_list? candidate_profile doesn't check for `access_all_profiles` (https://github.com/aces/Loris/blob/55974fdf1e0a7c69564ccbe351c6ed454839f7e9/modules/candidate_profile/php/candidate_profile.class.inc#L38) whereas timepoint_list does (https://github.com/aces/Loris/blob/55974fdf1e0a7c69564ccbe351c6ed454839f7e9/modules/timepoint_list/php/timepoint_list.class.inc#LL47C38-L47C57). not sure if this is intended or a bug
