### ISSUE TITLE
instruments

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8518]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans https://github.com/aces/Loris/pull/8547
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
 https://github.com/aces/Loris/issues/8545
https://github.com/aces/Loris/pull/8547
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date ***No automated test was found for this module**
 - [x] Make sure RB is complete https://github.com/aces/Loris/issues/8444
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**
~https://github.com/aces/Loris/issues/8581~
https://github.com/aces/Loris/issues/8582
https://github.com/aces/Loris/issues/7886
https://github.com/aces/Loris/issues/7773
~https://github.com/aces/Loris/issues/8545~
~https://github.com/aces/Loris/issues/8578~
~https://github.com/aces/Loris/issues/8579~
~https://github.com/aces/Loris/issues/8580~

- **Second Round Test**
https://github.com/aces/Loris/issues/8708

 - **Candidate Release testing**
 - #8755

## Comments
 - No automated test was found for this module
 - ~Could not test items 8 and 9~ Tested in second round 

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
