### ISSUE TITLE
document_repository

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8519]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory) **[Template only for dashboard notification]**
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
#8760

## Comments
Estimate: 30 minutes
#8758 - Test plan update
#8761 - Help content update
- After a file edit, the response in the modal is: "Updated Successful!" (sic)
- After a file deletion, the response in the modal, which only appears very briefly before a page refresh, is: "delete Successful!"
- This does not contradict the test plan, but it is likely not the desired behaviour. The test plan states: 
> 18. Check that if a document notification occurred since the last login, it is labeled as 'New' in the Document Repository panel. [Manual Test]
> 19. Check that a 'New' notification is not labeled 'New' anymore after login in again. [Manual Test]

As a user that is logged in at the time of an upload, the widget shows the 'New' label indefinitely, no matter how many times I visit the dashboard. Then, if I log out, and back in, the 'New' label is still there indefinitely, and only disappears the next time I log in.

Issues still outstanding from previous release testing: None

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
