### ISSUE TITLE
tools

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8521]
## Tasks:
- [x] Review issues from previous testing
### Documentation Tasks
 - [x] Update test plans
Module has been redesigned: test plan update is in order.
 - [x] Review/update module READMEs
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Open the web console and make sure no JS or network error shows up during testing. Create an issue reporting them if any.
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons)
