### ISSUE TITLE
imaging_browser

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8524]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [ ] React (no templates directory) --> There is a 'Templates' directory
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
- https://github.com/aces/Loris/issues/7874
## Comments
- Since testing in this round was done on COPN, raisinbread data was not checked
- Phantom data not tested as there is not phantom data on QPN
- Parts of testplan involving back-end access were not tested
- Widget from candidate dashboard not tested on QPN

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by SantiagoTG** [comment]
## Tasks:
- [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 List related issues/bugs here
- https://github.com/aces/Loris/issues/7873

**Minor Issues:** 

**Previously reported bugs still outstanding:** 


## Comments
 - **Insert comments here**

## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
