### ISSUE TITLE
conflict_resolver

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8525]
## Tasks:
- [ ] Review issues from previous release testing

### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
   - need to update it, few things missing (permissions)
 - [ ] Check user help content for accuracy and formatting (front end)
   - need to re-check when the help format bug is resolved
 
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up-to-date
 - [ ] Make sure RB is complete
   
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues

 - new issues:

#8766 
 
 - Issues from last testing round still open: 
 
## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by SantiagoTG** [comment]
## Tasks:
- [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
List related issues/bugs here
- https://github.com/aces/Loris/issues/7690

**Minor Issues:**

**Previously reported bugs still outstanding:** 
- [ ]  https://github.com/aces/Loris/issues/7703 (Is this still outstanding?: PR https://github.com/aces/Loris/pull/7854 issued but not tested due to: https://github.com/aces/Loris/issues/8040)

## Comments
 - **insert comments here**

 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
