### ISSUE TITLE
instrument_builder

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8526]

**Comment by SantiagoTG** [comment]
## Tasks:
- [ ] Review issues from previous release testing

### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)--> There is a Templates Directory.  
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues

MINOR: 

Previously reported bugs still outstanding: 
 - [ ] No sign of a Radio element in any docs or the module front-end: #5846
 - [ ] When the Question Name is redundant, the related error stays there as the user changes the field, even changing the question type does not change the error message.
 - [ ] There is no 'not_answered' option for Text Area (Step 1.e.2 in [Text Plan](https://github.com/xlecours/Loris/blob/8c2fdb49c82e7b03a2ed66861066a6b312aaad42/modules/instrument_builder/test/TestPlan.md))
 - [ ] There is a typo in the test plan (linst)

## Comments



## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
