### ISSUE TITLE
help_editor

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8529]
## Tasks:
- [x] Review issues from previous testing
### Documentation Tasks
 - [x] Update test plans
 Wrote issue for the update of the test plan.
 - [x] Review/update module READMEs
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Open the web console and make sure no JS or network error shows up during testing. Create an issue reporting them if any.
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - #8622 
 - #8624

## Comments
 - **insert here**

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons)
