### ISSUE TITLE
mri_violations

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8530]
## Tasks:
- [x] Review issues from previous testing
### Documentation Tasks
 - [x] Update test plans
Module has been redesigned: test plan update is in order.
 - [x] Review/update module READMEs
 - [x] Check User Help Content
### Testing Tasks
 - [x] Open the web console and make sure no JS or network error shows up during testing. Create an issue reporting them if any.
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
#8625 - closed
#8626 - closed
#8627 - closed
#8737
#8743

## Comments
I still need to check if the automated tests work with the redesigned module. - Nicolas
Same - Saagar

## Status
 - [ ] Testing COMPLETE
 - [x] Partially Tested
 - [ ] Could Not Test (please specify reasons)
