### ISSUE TITLE
api_docs

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8532]
**Tasks:**
- [x] Review issues from previous release testing
- [x] Make sure RB is complete

**Documentation Tasks**
- [x] Update test plans
- [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
- [ ] Check user help content for accuracy and formatting (front end)

**Status**
- [ ] Testing COMPLETE
- [x] Partially Tested
- [ ] Could Not Test (please specify reasons in comment)

**Bugs**
- #8602
- #8619

**Comment by zaliqarosli** [comment]
hey @AlexandraLivadas i separately found this bug that i made a PR for just fyi https://github.com/aces/Loris/issues/8602
