### ISSUE TITLE
candidate_parameters

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8536]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [x] React (no templates directory)
 - [x] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues

**Closed, Done & Reviewed:**
- [Candidate Parameters] - Update test plan :  https://github.com/aces/Loris/issues/8701
- [Candidate Parameters] - Edit date of birth issue : https://github.com/aces/Loris/issues/8574
- [Candidate Parameters] - Update README.md with permissions' frontend name : https://github.com/aces/Loris/issues/8557
- [Candidate Parameters] Outdated test plan : https://github.com/aces/Loris/issues/7709

**Previously created & still open/re-opened:**
- [Candidate Parameters] Help text kinda useless... : https://github.com/aces/Loris/issues/7707
- [Candidate Parameters] Inconsistent behaviour of button Candidate Info : https://github.com/aces/Loris/issues/7708
- [Candidate parameters] DoB and DoD formats ignored : https://github.com/aces/Loris/issues/6994
- [Candidate parameters] Family table not updatedhttps://github.com/aces/Loris/issues/7123
- [Candidate Parameters / Configuration] Add configuration to add consent to DB on front-end : https://github.com/aces/Loris/issues/5070
- [Candidate Parameters] Add genetic information to the module : https://github.com/aces/Loris/issues/4809

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by charliehenrib** [comment]
@ridz1208 I tested what I could, but there is a lot that I could not do due backend testing. I also noticed that no one else is testing this module and I am not confident to leave it with only my testing. So, I think it should be retested by a developer to make sure all is okay.
