### ISSUE TITLE
module_manager

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8537]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**
https://github.com/aces/Loris/issues/7083
https://github.com/aces/Loris/issues/8543
https://github.com/aces/Loris/issues/8544
https://github.com/aces/Loris/issues/8695
## Comments
 - **insert comments here**
Testing took 43 minutes
## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
