### ISSUE TITLE
my_preferences

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8538]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [ ] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues

**New Issues:**
- [ ] [My Preferences] - Password change expected for any change in preferences : https://github.com/aces/Loris/issues/8745

**Previously created & still open/re-opened:** 
- [ ] [My Preferences] Add user notifications for imaging upload via ‘My Preferences : https://github.com/aces/Loris/issues/7448
- [ ] [My Preferences] - Notification missing for media module : https://github.com/aces/Loris/issues/8553

**Closed, Done & Reviewed:**
- [My Preferences] - Password rules not enforced : https://github.com/aces/Loris/issues/8548
- [My Preferences] - Missing error for invalid email syntax : https://github.com/aces/Loris/issues/8550
- [My Preferences] - Modified information not showing in user account module : https://github.com/aces/Loris/issues/8551

## Comments

took 35 minutes to test
 
## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
