### ISSUE TITLE
candidate_list

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8539]
## Tasks:
- [x] Review issues from previous release testing

### Documentation Tasks
 - [x] Update test plans
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end)

### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete

### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [x] No ajax dir
 - [x] Data framework implemented
 - [x] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
#6829
#8590

## Comments
I'm not sure why there is the file [Feedback_BVL_Test_Plan.md](https://github.com/aces/Loris/blob/main/modules/candidate_list/test/Feedback_BVL_Test_Plan.md) in the test directory of this module since there is no feedback on this page.

Also, there were some extra Projects / Cohorts in the access profile page that were not in the user accounts page with testing names. I'm assuming this is because of testing for other modules on the VM.

## Status
 - [x] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)
