### ISSUE TITLE
survey_accounts

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8541]
## Tasks:
- [x] Review issues from previous release testing
### Documentation Tasks
 - [x] Update test plans https://github.com/aces/Loris/pull/8797
 - [x] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [x] Check user help content for accuracy and formatting (front end) PR: https://github.com/aces/Loris/pull/8789
### Testing Tasks
 - [x] Follow test plan (SEPARATE TICKETS)
 - [x] Check if automated tests are up to date
 - [x] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [x] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - #8546 
 - #8549

- Candidate release testing: None

## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE (candidate release testing)
 - [x] Partially Tested - Couldn't Complete Step 8 & 9 due to the bug #8546 
 - [ ] Could Not Test (please specify reasons in comment)
